services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./db-data:/var/lib//postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/root/redis
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - DATABSE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - ROCKET_DATABASES={postgres={url=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable}}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis

